export const DANGEROUS_CATEGORIES = {
  GAMBLING: {
    weights: {
      "casino": 0.8,
      "bet": 0.8,
      "betting": 0.8,
      "betika": 0.9,
      "gambling": 0.9,
      "unibet": 0.9,
      "sportsbook": 0.7,
      "poker": 0.5,
      "deposit matches": 0.8,
      "odds": 0.6,
      "roulette": 0.6,
      "blackjack": 0.6,
      "wager": 0.8,
      "slots": 0.5,
      "jackpot": 0.7,
      "jackpots": 0.7,
      "markets": 0.6,
      "bet slip": 0.7,
      "stake": 0.6,
      "deposit": 0.5,
      "withdraw": 0.5,
      "live betting": 0.8,
      "cash out": 0.5,
      "free bet": 0.6,
      "promo code": 0.4,
      "virtual sports": 0.6,
      "bonus": 0.5,
      "register to bet": 0.8,
      "matches": 0.4,
      "teams": 0.4,
      "live score": 0.5,
      "1xbet": 0.9,
      "betway": 0.9,
      "sportybet": 0.9,
      "melbet": 0.9,
      "22bet": 0.9,
      "bet365": 0.9,
      "william hill": 0.9,
      "ladbrokes": 0.9,
      "paddy power": 0.9,
      "draftkings": 0.9,
      "fanduel": 0.9,
      "pointsbet": 0.8,
      "parlay": 0.7,
      "accumulator": 0.7,
      "moneyline": 0.7,
      "handicap bet": 0.8,
      "spread betting": 0.8,
      "in-play": 0.7,
      "cashback offer": 0.5,
      "welcome bonus": 0.6,
      "slot machine": 0.7,
      "fruit machine": 0.7,
      "video poker": 0.7,
      "baccarat": 0.6,
      "craps": 0.6,
      "keno": 0.6,
      "bingo": 0.6,
      "lottery": 0.5,
      "scratch card": 0.6,
      "sports odds": 0.8,
      "betting tips": 0.8,
      "bookmaker": 0.8,
      "bookmakers": 0.8,
      "esports betting": 0.8,
      "crypto casino": 0.9,
      "bitcoin gambling": 0.9
    },
    threshold: 2.5
  },
  PORNOGRAPHY: {
    weights: {
      "porn": 0.9,
      "xxx": 0.8,
      "milf": 0.9,
      "cam porn": 0.9,
      "nsfw": 0.6,
      "nude": 0.6,
      "sex videos": 0.9,
      "adult videos": 0.9,
      "escort service": 0.9,
      "pornhub": 0.95,
      "xvideos": 0.95,
      "xhamster": 0.95,
      "redtube": 0.95,
      "youporn": 0.95,
      "brazzers": 0.95,
      "onlyfans": 0.8,
      "naked": 0.6,
      "erotic": 0.7,
      "hardcore sex": 0.9,
      "amateur porn": 0.9,
      "teen porn": 0.95,
      "hentai": 0.8,
      "live sex": 0.9,
      "sex cam": 0.9,
      "webcam sex": 0.9,
      "adult content": 0.8,
      "adult site": 0.8,
      "18+": 0.5,
      "explicit content": 0.7,
      "free porn": 0.9,
      "pornographic": 0.9,
      "sexual content": 0.7,
      "escort": 0.7,
      "call girl": 0.8,
      "strip club": 0.7,
      "nudes": 0.7,
      "lewd": 0.6,
      "fetish": 0.7,
      "bdsm": 0.8,
      "sex toys": 0.6,
      "erotica": 0.7,
      "masturbation": 0.9,
      "orgasm": 0.8,
      "sexy girls": 0.8
    },
    threshold: 2.4
  },
  DRUGS: {
    weights: {
      "meth": 0.9,
      "cocaine": 0.8,
      "heroin": 0.9,
      "buy drugs": 0.9,
      "buy weed": 0.8,
      "mdma": 0.8,
      "lsd": 0.7,
      "illegal narcotics": 0.9,
      "darknet market": 0.95,
      "dark web market": 0.95,
      "buy cocaine": 0.95,
      "buy heroin": 0.95,
      "buy meth": 0.95,
      "order drugs": 0.9,
      "drug marketplace": 0.95,
      "drug market": 0.9,
      "silk road": 0.9,
      "fentanyl": 0.9,
      "oxycontin": 0.8,
      "xanax pills": 0.8,
      "buy xanax": 0.9,
      "buy fentanyl": 0.95,
      "buy opioids": 0.9,
      "opioid": 0.7,
      "amphetamine": 0.8,
      "crystal meth": 0.9,
      "crack cocaine": 0.9,
      "ketamine": 0.7,
      "psilocybin": 0.7,
      "ecstasy pills": 0.8,
      "drug supplier": 0.9,
      "drug vendor": 0.9,
      "discreet shipping": 0.7,
      "stealth shipping": 0.8,
      "anonymous delivery": 0.7,
      "pills for sale": 0.8,
      "research chemicals": 0.7,
      "psychedelics": 0.6,
      "marijuana online": 0.7,
      "weed delivery": 0.7,
      "hash online": 0.8,
      "shrooms online": 0.8,
      "magic mushrooms buy": 0.9,
      "narcotics online": 0.9
    },
    threshold: 2.5
  }
};
