export const SAFE_HOSTNAMES = [
  'coursera.org',
  'www.coursera.org',
  'learn.coursera.org',
  'edx.org',
  'www.edx.org',
  'udemy.com',
  'www.udemy.com',
  'khanacademy.org',
  'www.khanacademy.org',
  'academy.binance.com',
  'developer.mozilla.org',
  'github.com'
];

export const SAFE_MODIFIERS = {
  "addiction treatment": -10.0,
  "rehabilitation": -5.0,
  "documentary": -2.0,
  "law enforcement": -3.0,
  "educational purposes": -5.0,
  "course": -3.5,
  "online course": -6.0,
  "specialization": -5.0,
  "professional certificate": -5.0,
  "lesson": -3.0,
  "training program": -4.0,
  "data science": -2.5,
  "machine learning": -2.5,
  "computer vision": -2.5,
  "research paper": -3.5,
  "public health": -3.0,
  "medical school": -3.0,
  "history of": -2.0,
  "prevent addiction": -7.0,
  "recovery support": -7.0,
  "news article": -4.0,
  "journalism": -3.0,
  "breaking news": -2.0,
  "police arrest": -5.0,
  "seize": -2.0,
  "court": -2.0,
  "how to block": -10.0,
  "how to prevent": -8.0,
  "how to stop": -8.0,
  "addiction": -4.0,
  "recovery": -4.0,
  "treatment": -4.0,
  "research": -3.0,
  "study": -3.0,
  "what is": -2.0,
  "education": -3.0,
  "learning": -3.0,
  "tutorial": -3.0,
  "guide": -3.0
};
