export const CATEGORIES = {
  GAMBLING: 'GAMBLING',
  PORNOGRAPHY: 'PORNOGRAPHY',
  DRUGS: 'DRUGS',
  SAFE: 'SAFE'
};

export const MESSAGE_TYPES = {
  CONTENT_BLOCKED: 'CONTENT_BLOCKED',
  SYNC_RULES: 'SYNC_RULES'
};

export const ALARM_NAMES = {
  DAILY_SYNC: 'DAILY_RULE_SYNC'
};
