export const ERRORS = {
  NETWORK_TIMEOUT: 'NETWORK_TIMEOUT',
  SYNC_FAILED: 'SYNC_FAILED',
  QUEUE_OVERFLOW: 'QUEUE_OVERFLOW',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  AUTH_INVALID: 'AUTH_INVALID',
  STORAGE_ERROR: 'STORAGE_ERROR'
};
